/**/*:
  ros__parameters:
    broker:
      host: 10.35.96.180
      port: 1883
      user: soo  
      pass: soo  
    bridge:
      ros2mqtt:
        ros_topics:
          - /ping/primitive
          - /ego_vehicle/MAV/control/trajectory_suggestion
          - /ego_vehicle/MAV/state/subsystem_state
          - /ego_vehicle/v2x/json/rgs
        /ego_vehicle/v2x/json/rgs:
          mqtt_topic: v2x/json/rgs
          primitive: true
        /ego_vehicle/MAV/control/trajectory_suggestion:
          mqtt_topic: /MAV/control/trajectory_suggestion
          primitive: true
        /ego_vehicle/MAV/state/subsystem_state:
          mqtt_topic: /MAV/state/subsystem_state
          primitive: true
        /ping/primitive:
          mqtt_topic: pingpong/primitive
          primitive: true
      mqtt2ros:
        mqtt_topics:
          - pingpong/primitive
          - v2x/json/rgs
          - /MAV/control/waypoint_suggestion
          - /MAV/control/trajectory_suggestion
          - /MAV/control/trajectory_acknowledgement
        v2x/json/rgs:
          ros_topic: /ego_vehicle/v2x/json/rgs
          primitive: true
        /MAV/control/waypoint_suggestion:
          ros_topic: /ego_vehicle/MAV/control/waypoint_suggestion
          primitive: true
        /MAV/control/trajectory_suggestion:
          ros_topic: /ego_vehicle/MAV/control/trajectory_suggestion
          primitive: true
        /MAV/control/trajectory_acknowledgement:
          ros_topic: /ego_vehicle/MAV/control/trajectory_acknowledgement
          primitive: true
