uint8 class_id
uint8 certainty	# confidence of classification 0..100

# possible class_id values
uint8 UNCLASSIFIED=0
uint8 UNKNOWN_SMALL=1
uint8 UNKNOWN_BIG=2
uint8 UNDER_DRIVABLE=3
uint8 OVER_DRIVABLE=4
uint8 PEDESTRIAN=5
uint8 BIKE=6
uint8 BICYCLE=7
uint8 MOPED=8
uint8 MOTORCYCLE=9
uint8 CAR=10
uint8 VAN=11
uint8 BUS=12
uint8 TRUCK=13
uint8 LIGHT_TRUCK=14
uint8 HEAVY_TRUCK=15
uint8 TRAM=16
uint8 TRAILER=17
uint8 SPECIAL_VEHICLE=18
uint8 EGO_VEHICLE=19