uint64 object_id
string class_name
float64 existence_probability
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist
geometry_msgs/AccelWithCovariance accel

# reference point
uint8 REFERENCE_POINT_FRONT_LEFT = 0
uint8 REFERENCE_POINT_FRONT_CENTER = 1
uint8 REFERENCE_POINT_FRONT_RIGHT = 2
uint8 REFERENCE_POINT_CENTER_LEFT= 3
uint8 REFERENCE_POINT_CENTER = 4
uint8 REFERENCE_POINT_CENTER_RIGHT = 5
uint8 REFERENCE_POINT_REAR_LEFT = 6
uint8 REFERENCE_POINT_REAR_CENTER = 7
uint8 REFERENCE_POINT_REAR_RIGHT = 8
uint8 reference_point
